# Generated by Django 5.1.6 on 2025-03-30 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the blog post.', max_length=200)),
                ('content', models.TextField(help_text='Write the content of the blog post here.')),
                ('published_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the post was published.')),
                ('author', models.ForeignKey(help_text='The author of the blog post. A user can have multiple posts.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
